prometheus:
  alertmanager:
    enabled: false
  prometheus-pushgateway:
    enabled: false
  configmapReload:
    prometheus:
      enabled: false
  server:
    nodeSelector:
      kubernetes.io/hostname: {master node}
    securityContext:
      #runAsUser: {userid}
      #runAsNonRoot: true
      #runAsGroup: {groupid}
      #fsGroup: {fsid}
    persistentVolume:
      enabled: true
      existingClaim: "prometheus-pvc"
      volumeName: "prometheus-pv"